# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user_city', models.CharField(default='', max_length=40)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
