# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
