# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='profile_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='user_image',
        ),
    ]
