# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_category_name', models.CharField(choices=[('Starters', 'Starters'), ('Main courses', 'Main courses'), ('Desers', 'Desers'), ('Smoothies', 'Smoothies'), ('Juices', 'Juices')], default='', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=54)),
                ('description', models.TextField(default='', max_length=148)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('recipe_name', models.CharField(default='', max_length=254)),
                ('cousine', models.CharField(default='', max_length=25)),
                ('preparation_time', models.CharField(default='', max_length=25)),
                ('recipe_how_to_serve', models.CharField(default='', max_length=354)),
                ('preparation', models.CharField(default='', max_length=500)),
                ('ingredient_1', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_2', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_3', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_4', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_5', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_6', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_7', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_8', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_9', models.CharField(blank=True, default='', max_length=54)),
                ('ingredient_10', models.CharField(blank=True, default='', max_length=54)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
