# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-18 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('recipe_name', models.CharField(default='', max_length=254)),
                ('recipe_category_name', models.CharField(choices=[('Starters', 'Starters'), ('Main courses', 'Main courses'), ('Desers', 'Desers'), ('Smothies', 'Smothies'), ('Juices', 'Juices')], default='', max_length=20)),
                ('cousine', models.CharField(default='', max_length=25)),
                ('uploaded_by', models.CharField(default='', max_length=25)),
                ('preparation_time', models.CharField(default='', max_length=25)),
                ('recipe_how_to_serve', models.CharField(default='', max_length=254)),
                ('preparation', models.CharField(default='', max_length=500)),
                ('ingredients', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
