# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-28 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe_category_name',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main courses', 'Main courses'), ('Desers', 'Desers'), ('Smoothies', 'Smoothies'), ('Juices', 'Juices')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
