# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preparation',
            field=models.TextField(default='', max_length=500),
        ),
    ]
