# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200129_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preparation',
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_method_1',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_method_2',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_method_3',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_method_4',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_method_5',
            field=models.TextField(default='', max_length=300),
        ),
    ]
