# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200129_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preparation_method_2',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_method_3',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_method_4',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_method_5',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
