# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191229_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.CharField(default='user', max_length=254),
        ),
    ]
