# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20191229_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_be_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_category_name',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main courses', 'Main courses'), ('Desers', 'Desers'), ('Smoothies', 'Smoothies'), ('Juices', 'Juices')], default=True, max_length=20),
        ),
    ]
