# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-11 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200109_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uploaded_by',
        ),
    ]
