# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-15 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200112_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=650),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=54),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_how_to_serve',
            field=models.CharField(default='', max_length=354),
        ),
    ]
