# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-15 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200115_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
