# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200115_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='', max_length=400),
        ),
    ]
