# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-18 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20200117_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=148),
        ),
    ]
