# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-19 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20200118_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
