# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20200119_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.CharField(default='', max_length=54),
        ),
    ]
