# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-19 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20200119_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
